api_limits:
  gemini:
    requests_per_minute: 60
    requests_per_day: 1000
    max_tokens_per_request: 2048

  openai:
    requests_per_minute: 50
    requests_per_day: 1000
    max_tokens_per_request: 4096

processing:
  max_concurrent_emails: 3
  max_batch_size: 50
  timeout_seconds: 300

quality_thresholds:
  min_personalization_score: 6
  min_quality_score: 7
  max_generic_phrases: 2
  required_specific_details: 3